name: IPFSTT Client Due Diligence Form
description: IPFSTT Client Due Diligence
title: "[IPFSTT Client Due Diligence Form]: <Project Name>"
labels: ["DataCap", "Client"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this form!
  - type: input
    id: 
    attributes: 
      label: Applicant name
      description: What is your name?
      placeholder:
    validations:
      required: true
  - type: input
    id:  
    attributes:
      label: Organization
      description: What organization are you affiliated with?
      placeholder:  
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Dataset Name
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: DataSet Size
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: The role related to the dataset
      description: Dataset Owner/Data Preparer/Other
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Cooperation Sp
      description: 
      placeholder: 
    validations:
      required: true
  - type: input
    id: 
    attributes:
      label: Email verification
      description: 
      placeholder: 
    validations:
      required: true
